services:
  windows:
    image: dockurr/windows
    container_name: windows
    network_mode: host # Quan trọng nhất để dùng IP Tailscale
    environment:
      DISK_SIZE: "120G"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - /isos/a.iso:/custom.iso
      - /isos/driver.iso:/driver.iso
    restart: on-failure
