name: Vong_Lap_Co_Tailscale

on:
  workflow_dispatch:
  repository_dispatch:
    types: [vong_lap_moi]

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lay code ve
        uses: actions/checkout@v4

      - name: 2. Ket noi Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: 3. Chay Docker Windows
        run: |
          docker compose up -d
          echo "Dang cho Windows khoi dong..."
          sleep 60
          echo "IP Tailscale cua ban la:"
          tailscale ip -4
          echo "Dang treo may..."
          sleep 19800

      - name: 4. Tu goi may tiep theo
        if: always()
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "vong_lap_moi"}'
